### ISSUE TITLE
Shadow on non-transparent themes?

### ISSUE THREAD

**Issue by cassidyjames** [calo001/luna#1]
Right now the applet looks a little bit off without any shadow on the colored themes. It makes sense to remove the shadow when it's transparent, but I think keeping it with the colored themes would look a bit more native to elementary OS.

**Comment by calo001** [comment]
Originally, my idea was to have a shadow according to the color of the calendar, however I did not find a suitable configuration of values in box-shadow that I would like very much and that would be similar to the one used by elementary OS. So I decided to put a small shadow around, but I'll try to see if I can make it look more native.

One of the problems that I found when using the box-shadow by default is shown in the following image. In the first it felt that the upper white border does not look very nice and in the second the black border when the dark mode is enabled in the system.

![calendarissue](https://user-images.githubusercontent.com/9545757/46778531-c03d1c00-ccd9-11e8-9643-fb3dfe3e04af.png)

**Comment by cassidyjames** [comment]
"dark mode" isn't something that elementary OS natively supports unless your app requests it, so I wouldn't be to concerned about the second screenshot. The first looks close to correct to me. You might look at Dan's styling in [Nimbus](https://github.com/danrabbit/nimbus) for some inspiration, though.

**Comment by calo001** [comment]
I realized that the key is to use @define-color bg_highlight_color shade (@color, 1.4); that way the border looks prettier and more native to elementary. Soon an update :smile:
