### ISSUE TITLE
could you make a flatpak for luna? 

### ISSUE THREAD

**Issue by ghost** [calo001/luna#11]
Hi, I really appreciate your work , is a very good application
but i don't use elementary OS
could you make a flatpak for luna?
in this way, users can install the application in any linux distribution

please.
thank you.

**Comment by calo001** [comment]
Hey thanks.
I am definitely interested in bringing "luna" to flathub, however I still do not know how to do the packaging, maybe it takes me a while to do it.

**Comment by calo001** [comment]
@chemel9 Now is available in [Flathub](https://flathub.org/apps/details/com.github.calo001.luna)

**Comment by calo001** [comment]
[](url)
