### ISSUE TITLE
Not clear how to quit Luna

### ISSUE THREAD

**Issue by eljefuri** [calo001/luna#15]
I do not see a "Quit" option anywhere in the (vertical) ... menu, nor any other way to quit the app. Perhaps a quit option should be included in the (vertical) ... menu.

**Comment by eljefuri** [comment]
ESC key apparently works but that seems a bit too easily pressed to me: I discovered it accidentally.

**Comment by calo001** [comment]
I realized that the Widgets made for elementary quit with the ESC key, I removed the exit button  because I did not want to have so many buttons in the widget, but it would be a good idea to add it as an option in the menu, thanks for the suggestion.

**Comment by eljefuri** [comment]
Yeah unfortunately this (like so many things in Elementary) isn't really obvious, so I would definitely suggest keeping an exit button in there somewhere. Thank you!

**Comment by calo001** [comment]
Luna 1.1 now has a close button!
