### ISSUE TITLE
Package as Flatpak for elementary OS 6

### ISSUE THREAD

**Issue by danirabbit** [calo001/luna#25]
As you might have heard, AppCenter is going Flatpak! For elementary OS 6, we will not longer be accepting Debian packaging, so your app will need to be updated.

We have documentation on our developer guide for writing your Flatpak manifest here: https://docs.elementary.io/develop/writing-apps/our-first-app/packaging#flatpak-manifest

Also, in case you missed it, elementary OS 6 beta 2 is [now available](https://builds.elementary.io). This is a great time to get your app packaged up as Flatpak and test that everything is working before the final release. AppCenter submission for OS 6 will be open soon, so don't delay :)

**Comment by calo001** [comment]
Hi again! @danrabbit 

Also here, I have Luna updated to work well with Odin.

The commit to publishing Luna 1.1.5 on Odin is: https://github.com/calo001/luna/commit/0f361dae270bcebd38e29ef995a6a929e7e35990

Thanks! :)

**Comment by danirabbit** [comment]
Awesome! Can you do me a huge favor and do a release tag in GitHub for that commit for me? :)

**Comment by calo001** [comment]
Oh sorry, I forgot to create it, but now Itś ready :) Thanks!
