### ISSUE TITLE
Screenshots need to be updated

### ISSUE THREAD

**Issue by danirabbit** [calo001/luna#28]
Hey, I was just reviewing your update for Luna and it looks good to go except the screenshot needs to be updated for OS 6 :)

**Comment by calo001** [comment]
Hi! Oh sorry, the screenshots are fixed on version 1.1.6 :)  
https://github.com/calo001/luna/commit/0fb19c1a10c489ca8c8495cc1a46a5966c21e192

Thanks! :man_dancing:
