### ISSUE TITLE
Two days selected after leaving Luna open over night

### ISSUE THREAD

**Issue by hannesschulze** [calo001/luna#5]
Thanks for this awesome app, it fits perfectly to my desktop! :)

But after I left my notebook in standby over night and turning it back on today, two days are selected: yesterday and today.

![screenshot von 2018-10-14 09 07 33](https://user-images.githubusercontent.com/43932053/46913632-45058f80-cf91-11e8-855b-6271e625538c.png)

**Comment by calo001** [comment]
I have the correction ready, soon an update. Thanks :)
