### ISSUE TITLE
Screenshot URLs are not readable by the screenshots server

### ISSUE THREAD

**Issue by danirabbit** [calo001/luna#7]
See: https://appstream.elementary.io/appcenter/html/bionic/main/issues/com.github.calo001.luna.html

These should instead be formatted like:
```
https://raw.githubusercontent.com/calo001/luna/master/data/images/screenshot_1.png
```

**Comment by calo001** [comment]
Thanks I had not realized that I used the url incorrectly, fixed, soon an update.
