### ISSUE TITLE
Remember last position on screen

### ISSUE THREAD

**Issue by dracid** [calo001/luna#8]
I've included Luna in Startup, but every time it launches in the middle of the screen.
Can it be made so that it remembers its last known position? 

That would be loads better! Thanks!

**Comment by dracid** [comment]
Honestly,  I do not know what changed, but it works now. My apologies.

**Comment by calo001** [comment]
It also happened to me sometimes, anyway I made some changes to the code that I hope will improve that behavior. As soon as I can, I launch an update.
